wfc:
  name: "asm"
  numChannels: 64
  numActuators: 36
  numModes: 7
  port: 5556
  #flatFile: "/home/felix/src/pyrtc/pyRTC-IRTF/IRTF/calib/irtf1flat.20250809c.npy"
  floatingActuatorsFile: ""
  #m2cFile: "/home/felix/src/pyrtc/pyRTC-IRTF/IRTF/calib/z2a.empirical_norm.20250408b-2.npy"
  #m2cFile: "/home/felix/src/pyrtc/pyRTC-IRTF/IRTF/calib/z2a.20240409b.7modes.npy"
  #m2cFile: "/home/felix/src/pyrtc/pyRTC-IRTF/IRTF/calib/z2a_12x12emp_20251002b.npy"  
  #m2cFile: "/home/felix/src/pyrtc/pyRTC-IRTF/IRTF/calib/z2a.20240409b.npy"
  m2cFile: "/home/felix/src/pyrtc/pyRTC-IRTF/IRTF/calib/z2a.empirical_norm.20250408b.7modes.npy"
  #m2cFile: "/home/felix/src/pyrtc/pyRTC-IRTF/IRTF/calib/z2a.empirical_norm.20250408b.npy"  floatingInfluenceRadius: 1
  affinity: 1
  commandCap: 0.3
  hardwareDelay: 0.005 #seconds
  # gpuDevice: 0
  frameDelay: 0
  functions:
  - sendToHardware
