wfs:
  name: felix
  binning: 1
  downsampleFactor: 1
  exposure: 0.01
  gain: 0
  bitDepth: 16
  left: 1
  top: 1
  width: 512
  height: 512 
  imageSize: 512 # mimic FELIX 512x512
  darkCount: 5
  #darkFile: "/home/ellenlee/pyRTC/IRTF/calib/darkFELIX.npy"
  affinity: 0
  # gpuDevice: 0
  amplitude: 40
  #calPoints: "/Users/ellenlee/Documents/pyRTC-IRTF/IRTF/calib/felixcal/calpts_32.npy"
  #calPoints: "/Users/ellenlee/Documents/pyRTC-IRTF/IRTF/calib/felixcal/calpts_64_r45_12x12closed.npy"
  calPoints: "/home/felix/src/pyrtc/pyRTC-IRTF/IRTF/calib/felixcal/calpts_32.npy"
  bias: 500
  detectorNoise: 10
  spotSize: 2
  slopeNoise: 0 #pixels
  lag: 5 #frames
  functions:
  - expose
