loop:
  gain: 0.
  leakyGain: 0.0
  numDroppedModes: 0 #28
  pokeAmp: 0.1
  numItersIM: 200
  affinity: 2
  delay: 2
  method: push-pull
  playbackBufferFile: "/Users/ellenlee/Documents/pyRTC-IRTF/IRTF/calib/pb/cacofoni_pb_189Hz_x378_nmodes7_amp1_fmin4_df0.5.npy"
  IMFile: "/Users/ellenlee/Documents/pyRTC-IRTF/IRTF/calib/imat/imat.poke.20251002.c.npy"
  # playbackBufferFile: "/home/felix/src/pyrtc/pyRTC-IRTF/IRTF/calib/pb/cacofoni_pb_189Hz_x378_nmodes7_amp1_fmin4_df0.5.npy"
  # IMFile: "/home/felix/src/pyrtc/pyRTC-IRTF/IRTF/calib/imat/imat.poke.20251002.c.npy"
  pGain: 0.
  iGain: 0.
  dGain: 0.
  controlLimits: [-0.05, 0.05]
  absoluteLimits: [-0.3, 0.3]
  integralLimits: [-0.1, 0.1]
  derivativeFilter: 0.1
  # gpuDevice: 0
  functions:
   - leakyIntegrator
