loop:
  gain: 0.
  leakyGain: 0.0
  numDroppedModes: 0
  pokeAmp: 0.02
  numItersIM: 50
  affinity: 2
  delay: 2
  method: push-pull
  #IMFile: "/home/whetstone/pyRTC/SHARP_LAB/calib/IM_PYWFS.npy"
  pGain: 0.
  iGain: 0.
  dGain: 0.
  controlLimits: [-0.05, 0.05]
  absoluteLimits: [-0.3, 0.3]
  integralLimits: [-0.1, 0.1]
  derivativeFilter: 0.1
  # gpuDevice: 0
  functions:
   - leakyIntegrator
  # - linearExtrapolationPOL

  # left: 544
  # top: 100 
  # width: 384 
  # height: 384 

wfs:
  name: FELIXSimulator
  binning: 1
  downsampleFactor: 1
  exposure: 1
  gain: 0
  bitDepth: 16
  left: 189
  top: 319 
  width: 32 
  height: 32 
  darkCount: 5
  #darkFile: "/home/ellenlee/pyRTC/IRTF/calib/darkFELIX.npy"
  affinity: 0
  # gpuDevice: 0
  amplitude: 40
  calPoints: "/Users/ellenlee/Documents/pyRTC-IRTF/IRTF/calib/calpts_32.npy"
  bias: 500
  detectorNoise: 10
  spotSize: 2
  slopeNoise: 0 #pixels
  functions:
  - expose

slopes:
  type: felix
  signalType: slopes
 # validSubApsFile: "/Users/ellenlee/Documents/pyRTC-IRTF/IRTF/calib/subaps2x2_32pix.npy"
  subApMasksFile: "/Users/ellenlee/Documents/pyRTC-IRTF/IRTF/calib/subaps2x2_32pix.npy"
  refSlopesFile: "/Users/ellenlee/Documents/pyRTC-IRTF/IRTF/calib/refSlopes.npy"
  imageNoise: 5.1
  contrast: 100
  affinity: 4
  rotation: 45.0 # degrees, CCW
  # gpuDevice: 0
  functions:
  - computeSignal

wfc:
  name: "ImakaDM"
  port: 5556
  numChannels: 64
  numActuators: 36
  numModes: 36
  #flatFile: "/Users/ellenlee/Documents/pyRTC-IRTF/IRTF/calib/irtf1flat.20240306b.npy"
  saveFile: "/home/ellenlee/pyRTC/IRTF/calib/wfcShapePyWFS.npy"
  m2cFile: "/Users/ellenlee/Documents/pyRTC-IRTF/IRTF/calib/m2a_identity.npy" 
  floatingActuatorsFile: ""
  floatingInfluenceRadius: 1
  affinity: 1
  commandCap: 0.3
  hardwareDelay: 0.005 #seconds
  # gpuDevice: 0
  frameDelay: 0
  functions:
  - sendToHardware

psf:
  name: "FLIR"
  index: 0
  exposure: 3333
  gain: 0
  bitDepth: 16
  left: 936
  top: 432
  width: 128
  height: 128
  darkCount: 2000
  darkFile: "/home/whetstone/pyRTC/SHARP_LAB/calib/psfDark_PyWFS.npy"
  modelFile: "/home/whetstone/pyRTC/SHARP_LAB/calib/modelPSF_PyWFS.npy"
  integration: 5000
  affinity: 6
  functions:
  - expose
  - integrate
  - computeStrehl

optimizer:
  ncpa:
    name: "NCPA"
    numSteps: 100
    startMode: 0
    endMode: 40
    correctionMag: 0.003
    numReads: 1
    affinity: 10
  pid:
    name: "PID"
    numSteps: 100
    maxPGain: 0.5
    maxIGain: 0.1
    maxDGain: 0.1
    numReads: 1
    affinity: 10
  loop:
    name: "hyper"
    numSteps: 100
    minGain: 0.3
    maxGain: 0.8
    maxLeak: 0.05
    maxDroppedModes: 30
    numReads: 1
    affinity: 10
modulator:
  name: 'E-727'
  libFolder: '/opt/PI/lib64/'
  digitalFreq: 20000 #Hz
  frequency: 300 #Hz
  amplitude: 600
  relativeAmplitude: 1.0
  offsetX: 2500 #2800
  offsetY: 2500 #1100
  phaseOffset: 0
  servosOn: False
  autoZero: True 
  affinity: 7

