loop:
  gain: 0.
  leakyGain: 0.0
  numDroppedModes: 0 #28
  pokeAmp: 0.1
  numItersIM: 200
  affinity: 2
  delay: 2
  method: push-pull
  #playbackBufferFile: "/home/felix/src/pyrtc/pyRTC-IRTF/IRTF/calib/pb/calib/pb/cacofoni_pb_95.2Hz_x476_nmodes7_amp1_fmin4_df0.2.npy"
  IMFile: "/home/felix/src/pyrtc/pyRTC-IRTF/IRTF/calib/imat/imat.poke.20251002.c.npy"
  pGain: 0.
  iGain: 0.
  dGain: 0.
  controlLimits: [-0.05, 0.05]
  absoluteLimits: [-0.3, 0.3]
  integralLimits: [-0.1, 0.1]
  derivativeFilter: 0.1
  # gpuDevice: 0
  functions:
   - leakyIntegrator

wfs:
  name: felix
  binning: 1
  downsampleFactor: 1
  exposure: 0.2
  gain: 0
  bitDepth: 16
  left: 250 #95 #266
  top: 255 #170 #188
  width: 64 #64
  height: 64 #64
  darkCount: 100
  #darkFile: "/home/felix/src/pyrtc/pyRTC-IRTF/IRTF/calib/darkFELIX.npy"
  affinity: 0
  # gpuDevice: 0
  temperature: -65
  vi: 1
  functions:
  - expose

slopes:
  type: felix
  signalType: slopes
  subApMasksFile: "/home/felix/src/pyrtc/pyRTC-IRTF/pyRTCView/subaps2x2_64pix.fits" #50 degrees
  #subApMasksFile: "/home/felix/src/pyrtc/pyRTC-IRTF/IRTF/calib/felixcal/masks_itp_posA.fits"
  #refSlopesFile: "/home/felix/src/pyrtc/pyRTC-IRTF/IRTF/calib/felixcal/calpts_32_r45_12x12closed.npy"
  refSlopesFile: "/home/felix/src/pyrtc/pyRTC-IRTF/IRTF/calib/felixcal/refSlopes_FELIX.npy"
  chopMasksFile: "/home/felix/src/pyrtc/pyRTC-IRTF/IRTF/calib/felixcal/masks_itp.fits"
  imageNoise: 20.
  refSlopeCount: 1000
  contrast: 1
  affinity: 4
  rotation: 45.0 # degrees, CCW
  numSubAps: 4
  # gpuDevice: 0
  functions:
  - computeSignal


wfc:
  name: "asm"
  numChannels: 64
  numActuators: 36
  numModes: 7
  port: 5556
  #flatFile: "/home/felix/src/pyrtc/pyRTC-IRTF/IRTF/calib/irtf1flat.20250809c.npy"
  floatingActuatorsFile: ""
  #m2cFile: "/home/felix/src/pyrtc/pyRTC-IRTF/IRTF/calib/z2a.empirical_norm.20250408b-2.npy"
  #m2cFile: "/home/felix/src/pyrtc/pyRTC-IRTF/IRTF/calib/z2a.20240409b.7modes.npy"
  #m2cFile: "/home/felix/src/pyrtc/pyRTC-IRTF/IRTF/calib/z2a_12x12emp_20251002b.npy"  
  #m2cFile: "/home/felix/src/pyrtc/pyRTC-IRTF/IRTF/calib/z2a.20240409b.npy"
  m2cFile: "/home/felix/src/pyrtc/pyRTC-IRTF/IRTF/calib/z2a.empirical_norm.20250408b.7modes.npy"
  #m2cFile: "/home/felix/src/pyrtc/pyRTC-IRTF/IRTF/calib/z2a.empirical_norm.20250408b.npy"  floatingInfluenceRadius: 1
  affinity: 1
  commandCap: 1
  hardwareDelay: 0.005 #seconds
  # gpuDevice: 0
  frameDelay: 0
  functions:
  - sendToHardware

optimizer:
  ncpa:
    name: "NCPA"
    numSteps: 100
    startMode: 0
    endMode: 40
    correctionMag: 0.003
    numReads: 1
    affinity: 10
  pid:
    name: "PID"
    numSteps: 100
    maxPGain: 0.5
    maxIGain: 0.1
    maxDGain: 0.1
    numReads: 1
    affinity: 10
  loop:
    name: "hyper"
    numSteps: 100
    minGain: 0.3
    maxGain: 0.8
    maxLeak: 0.05
    maxDroppedModes: 30
    numReads: 1
    affinity: 10
modulator:
  name: 'E-727'
  libFolder: '/opt/PI/lib64/'
  digitalFreq: 20000 #Hz
  frequency: 300 #Hz
  amplitude: 600
  relativeAmplitude: 1.0
  offsetX: 2500 #2800
  offsetY: 2500 #1100
  phaseOffset: 0
  servosOn: False
  autoZero: True 
  affinity: 7

